#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 * This file is the binary used to run tests by the PHPMetro statistical analysis package
 * @package PHPMetro
 * @author https://gitlab.com/subiabre
 * @license MIT
 * @see https://gitlab.com/subiabre/phpmetro
 */

// Find autoload and config
$autoloads = [
        __DIR__ . "/../../",
        __DIR__ . "/..\/",
        __DIR__ . "/",
    ];

foreach ($autoloads as $file) {
    if (file_exists($file . 'vendor/autoload.php')) {
        define('PHPMETRO_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('PHPMETRO_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

// Require autoload
require PHPMETRO_COMPOSER_INSTALL;

// Run PHPMetro
$phpmetro = new PHPMetro\Service\Runner();

$phpmetro->run();
