name: CI

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        ini-values: post_max_size=256M, short_open_tag=On
        coverage: xdebug    
        tools: php-cs-fixer, phpunit

    - name: Composer install
      run: composer install

    - name: PHPUnit tests
      run: composer run-script test

    - name: Send coverage
      run: bash <(curl -s https://codecov.io/bash)
